##微服务端口号
server:
  port: 8001
mybatis:
  #config-location: classpath:mybatis/mybatis.cfg.xml #mybatis配置文件
  type-aliases-package: com.chenjm.springcloud.entities #所有实体类的所在包，注册别名
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml  #mapper 映射类 DeptMapper.xml
spring:
  application:
    name: cloud-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/dept01
    username: root
    password: root
    dbcp2:
      min-idle: 5  #连接池最小维持 连接数
      initial-size: 5 #初始化连接数
      max-total: 5 #最大连接数
      max-wait-millis: 200 #等待连接最大超时时间
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7003.com:7003/eureka,http://eureka7002.com:7002/eureka
      ## 单机版 defaultZone: http://localhost:7001/eureka  #eureka注册中心 服务端地址
  instance:
    instance-id: cloud-dept8001-hystrix #服务上面，status栏位中的名字
    prefer-ip-address: true #访问路径可以显示ip